### ISSUE TITLE
What is /.well-known/security.txt?

### ISSUE THREAD

**Issue by ianrandmckenzie** [elct9620/rails-letsencrypt#13]
Hi there,

I run several Rails applications, and a couple of them are reporting bots going to the Rails path `/.well-known/security.txt` – is this malicious behavior, or are the bots checking for a valid SSL certificate or something?

I should note, I do not use this gem, but I was reading your documentation and found that this gem uses this path.

**Comment by elct9620** [comment]
I think you can check the document about `.well-known` it used by various service for different usage.

https://en.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers
