### ISSUE TITLE
How to trigger callbacks for inherited certificate class in app

### ISSUE THREAD

**Issue by HarishR-amesh** [elct9620/rails-letsencrypt#14]
When we try to inherited the library certificate model and try to send emails in callbacks after the ssl certificates are updated. 

Callbacks wont be triggered as the updates called at the library level certificate model, inherited model won't be touched.

**Comment by elct9620** [comment]
I think the controller still call `LetsEncrypt::Certificate` to update it. Maybe I can add some configure options for users to allow them to change the handling model.

**Comment by harishmallow** [comment]
Thanks, @elct9620 For looking into it.  Maybe use could include a custom module (like certificate:: issuable) inclusion config options which user create and have in app/models/concerns directory, from which the user can add their logic to certificate model.

**Comment by HarishR-amesh** [comment]
Thanks, @elct9620 For looking into it. Maybe use could include a custom module (like certificate:: issuable) inclusion config options which user create and have in app/models/concerns directory, from which the user can add their logic to certificate model.

**Comment by elct9620** [comment]
The controller is using the `LetsEncrypt::Cerificate` model, so split it into concern didn't resolve the callback cannot be applied. I think to add config to set customize which model controller will be used is better.

Or you have some idea about use concern and can make it more flexible?

**Comment by HarishR-amesh** [comment]
Yeah, I think adding config to set customize model controller will be better. 

I thought of include custom module to `LetsEncrypt::Certificate` model and the user can use this module to extend using the `ActiveSupport::Concern` and include callbacks, class and instance methods and so.

**Comment by elct9620** [comment]
I think we have two options:

### Option 1

```ruby
# config/initializes/letsencrypt.rb
LetsEncrypt.config do |config|
  config.certificate_model = 'MyCertificate'
end

# app/models/my_certificate.rb
class MyCertificate < LetsEncrypt::Certificate
  # ...
end
```

### Option 2

```
# config/initializes/letsencrypt.rb
LetsEncrypt.config do |config|
  config.certificate_concerns = [
    'HasCertificatePreprocessor',
    'HasCertificatePostprocessor'
  ]
end

# app/models/concerns/has_certificate_preprocessor.rb
module HasCertificateprocessor
  # ...
end
```

---

I think option 1 is more clear for users to know about what are they doing.

**Comment by HarishR-amesh** [comment]
Yeah, Option 1 would be better for understanding. 

Thanks for looking into this @elct9620

**Comment by HarishR-amesh** [comment]
Ok, I will close this issue now.
