### ISSUE TITLE
End of Life Plan for ACMEv1

### ISSUE THREAD

**Issue by diegosomar** [elct9620/rails-letsencrypt#17]
I received an email from Let’s Encrypt telling the support for ACMEv1 clients will be stopped in June 2020. In my gemfile I have:

`
rails-letsencrypt (0.5.5)
      acme-client (~> 1.0)
`

How can we upgrade acme-client to keep the gem works?

ACMEv1 API deprecation details can be found in our community forum:
https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1

Tks!

**Comment by elct9620** [comment]
Yeah, this gem keeps the same behavior from acme-client 1.0 to 2.0. If you have any problem in newer version please let me know, I will help you to resolve it.

**Comment by diegosomar** [comment]
Ok @elct9620, tks! I have to upgrade acme-client via Gemfile? Do you know how?

**Comment by elct9620** [comment]
You can use `bundle update rails-letsencrypt` to upgrade it to latest version, the acme-client will upgrade, too.

If you had specified the `rails-letsencrypt` version, please specify the latest version `0.7.0` in Gemfile, and run `bundle install` to update the dependency.

**Comment by diegosomar** [comment]
Tks @elct9620!
