### ISSUE TITLE
How to use the Issued Certificate with Nginx

### ISSUE THREAD

**Issue by chongivan** [elct9620/rails-letsencrypt#23]
Hello, @elct9620 !

Thank you for the gem, it is wonderful =)

I have successfully done 
```
cert.issue
```

I see that there are changes in the database.

Where can i find
1) ssl_certificate
2) ssl_certificate_key

so that i can use them with Nginx?

Thanks again =)

**Comment by elct9620** [comment]
Hi, this gem depends on Redis to share the SSL certificate with Nginx.

You can follow this [guide](https://github.com/elct9620/rails-letsencrypt#ngx_mruby) to setup it.

**Comment by chongivan** [comment]
Thank you!

**Comment by chongivan** [comment]
> Hi, this gem depends on Redis and `ngx_mruby` to share the SSL certificate with Nginx.
> 
> You can follow this [guide](https://github.com/elct9620/rails-letsencrypt#ngx_mruby) to setup it.

Thank you for your prompt replies!

Question:

I have the issued `ssl_certificate` and `ssl_certificate_key` in my database.

After, i set up redis in production, and set 
```
config.save_to_redis = true
config.redis_url = 'redis://mydomain:6379/1'
```

How do i put the `ssl_certificate` and `ssl_certificate_key` in redis?
