### ISSUE TITLE
What does config/letsencrypt.key do?

### ISSUE THREAD

**Issue by chongivan** [elct9620/rails-letsencrypt#24]
Hello @elct9620 =)

I ran
```
rails generate lets_encrypt:register
```

and got config/letsencrypt.key

Then i ran
```
cert = LetsEncrypt::Certificate.find_by(domain: 'example.com')
```

But the cert.key in the database is different from config/letsencrypt.key

What is the config/letsencrypt.key for?

**Comment by elct9620** [comment]
The `config/letsencrypt.key` is used to access your Let's Encrypt account. Not related to your domain SSL certificate.

**Comment by chongivan** [comment]
Got it, thanks!
