### ISSUE TITLE
Error verifying URL

### ISSUE THREAD

**Issue by brobertsaz** [elct9620/rails-letsencrypt#25]
I have been struggling with getting this gem to work.  

rails-letsencrypt (0.9.0)
Rails version 5.2.3
Ruby version 2.6.3

I have tried installing several times and finally thought that maybe it was not working on localhost.  I deployed to a staging server and when I run `cert = LetsEncrypt::Certificate.create(domain: "bob1.appstaging.com")` I get the following error:

`Error: Acme::Client::Error::AccountDoesNotExist (No account exists with the provided key)`

I have ran the `rails generate lets_encrypt:register` both locally and on staging and it appears that it is working (there are not any error messages)

Any ideas what could be going wrong?

**Comment by elct9620** [comment]
Do you have the `config/letsencrypt.key` generated after `rails generate lets_encrypt:register`?

**Comment by brobertsaz** [comment]
```
Starting register Let's Encrypt account
Do you want to use in production environment? [y/N]: n
Where you to save private key [/var/deploy/unode__staging-gamma_/web_head/releases/20200611205848/config/letsencrypt.key]: y
Overwrite y? (enter "h" for help) [Ynaqh] y
Your privated key is saved in y, make sure setup configure for your rails.
What email you want to register: dev@pureoxygenlabs.com
Register successed, don't forget backup your private key
```
I check the key and it is populated.

**Comment by elct9620** [comment]
@brobertsaz 

```
Where you to save private key [/var/deploy/unode__staging-gamma_/web_head/releases/20200611205848/config/letsencrypt.key]: y
Your privated key is saved in y, make sure setup configure for your rails.
```

You give an invalid path to store your private key, if you want to change the path please update the config.

**Comment by brobertsaz** [comment]
I rerun this locally:
```
Starting register Let's Encrypt account
Do you want to use in production environment? [y/N]: y
Where you to save private key [/Users/bobroberts/PO2/u-app/config/letsencrypt.key]: config/letsencrypt.key
Overwrite config/letsencrypt.key? (enter "h" for help) [Ynaqh] y
Your privated key is saved in config/letsencrypt.key, make sure setup configure for your rails.
What email you want to register: dev@pureoxygenlabs.com
Register successed, don't forget backup your private key
```
What config needs to be updated?  I missed the `y` part as I was assuming that I was answering the `Where you to save private key [/Users/bobroberts/PO2/u-app/config/letsencrypt.key]: `

So I now have a key at `config/letsencrypt.key`, what config needs to be updated?

**Comment by elct9620** [comment]
If you have `config/letsencrypt.key` you will able to issue a certificate.

The error message `Error: Acme::Client::Error::AccountDoesNotExist (No account exists with the provided key)` means the account isn't created, but in this case is caused by the `config/letsencrypt.key` is missing that unable to identify a valid account.

**Comment by brobertsaz** [comment]
I am still getting the error. 

config/initializers/letsencrypt.rb:
```
config.private_key_path = Rails.root.join('config', 'letsencrypt.key')
```
The key is present in config/letsencrypt.key

I have tried locally and on staging server with no success.  I guess I will just use certbot which is working on the server.

**Comment by elct9620** [comment]
@brobertsaz 

In the default config, this gem will use Let's Encrypt staging server. Do you change the config to use the "production"?

According to your setup step:
```
Do you want to use in production environment? [y/N]: y
```

You have generated a production account but try to issue a certificate in the staging server.

**Comment by brobertsaz** [comment]
Wow, so the point is, I was being dumb ;)  It was a few different mistakes of mine. I appreciate the patience and assistance.
