### ISSUE TITLE
Migration syntax error for rails 6

### ISSUE THREAD

**Issue by lazylester** [elct9620/rails-letsencrypt#29]
Since Rails5, the migrations inherit from a class with a rails version appended, like:
`class CreateLetsencryptCertificates < ActiveRecord::Migration[5.0]`

However the detector for the versions in lib/generators/lets_encrypt/install_generator.rb does not write a version unless the rails version major is 5. So for rails 6, no version is appended.

**Comment by elct9620** [comment]
@lazylester The new version `0.10.1` fixed it 🎉

**Comment by lazylester** [comment]
Thank you very much! and thank you for this gem.
