### ISSUE TITLE
ArgumentError when setup private key for Let's Encrypt API

### ISSUE THREAD

**Issue by diegosomar** [elct9620/rails-letsencrypt#8]
Hello, after I changed the gemfile and runned install migrations, I am tried to setup private key for Let's Encrypt API. But, after answer the questions like that:

- Do you want to use in production environment? [y/N]: y
- Where you to save private key [/myapp/config/letsencrypt.key]: [ENTER]
- Overwrite /myapp/config/letsencrypt.key? (enter "h" for help) [Ynaqh] y
- What email you want to register: `myname@mayemail.com`

I got this error:

`/home/computer/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/acme-client-2.0.0/lib/acme/client.rb:31:in 'initialize': unknown keyword: endpoint (ArgumentError)
	from /home/computer/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails-letsencrypt-0.5.4/lib/letsencrypt.rb:24:in 'new'
	from /home/computer/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails-letsencrypt-0.5.4/lib/letsencrypt.rb:24:in 'client'
	from /home/computer/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails-letsencrypt-0.5.4/lib/letsencrypt.rb:52:in 'register'
	from /home/computer/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails-letsencrypt-0.5.4/lib/generators/lets_encrypt/register_generator.rb:49:in 'register_email'
	from /home/computer/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails-letsencrypt-0.5.4/lib/generators/lets_encrypt/register_generator.rb:16:in 'register'`

I don't know what I'm forgetting. Someone can help me?

- Using development env (localhost)
- ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
- Rails 4.2.1
- rails-letsencrypt 0.5.4
- acme-client 2.0.0

Tks!

**Comment by elct9620** [comment]
Oops, I didn't limit the `acme-client` under `~> 1.0`. I will add a patch to fix it, the `acme-client` 2.0 support is still work in progress.

**Comment by elct9620** [comment]
@diegosomar Please upgrade to 0.5.5 and it should work now.

**Comment by diegosomar** [comment]
@elct9620 Yes, it works! Tks!
